
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - ./:/app
    depends_on:
      - migrate
    networks:
      - crud
      
  migrate:
    build:
      context: ./
      dockerfile: Dockerfile.migrate
    volumes:
      - ./:/app
    depends_on:
      - alpha
    networks:
      - crud

  zero:
    image: dgraph/dgraph:latest
    volumes:
      - ./volumes:/dgraph
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --my=zero:5080
    networks:
      - crud

  alpha:
    image: dgraph/dgraph:latest
    volumes:
      - ./volumes:/dgraph
    ports:
      - 8080:8080
      - 9080:9080
    restart: on-failure
    command: dgraph alpha --my=alpha:7080 --zero=zero:5080 --security "whitelist=10.0.0.0/8,172.0.0.0/8,192.168.0.0/16" --limit mutations=strict
    networks:
      - crud

  ratel:
    image: dgraph/ratel:latest
    ports:
      - 8000:8000
    networks:
      - crud

networks:
  crud:
